

import "./globals.css";
import {Inter} from "next/font/google"

import { JetBrains_Mono } from "next/font/google";

const inter  = Inter({subsets: ['latin'], weights: [400, 500, 600, 700]})
const jetbrains_mono = JetBrains_Mono({subsets: ['latin'], weights: [400, 500, 600, 700]})
import { AuthContextProvider } from "./context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={`${jetbrains_mono.className} antialiased`}

      >
        <AuthContextProvider>
        {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
